name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          mvn -B clean compile package -P release-neodymium-applitools-plugin
          mvn -B clean compile package -P run-tests-in-parallel-forks
          mvn -B clean compile package -Dtest=OneBatchOnParallelTest
          mvn -B clean compile package -P run-tests-in-parallel-threads
          mvn -B clean compile package -Dtest=OneBatchOnParallelTest
