name: Java CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: run basic tests
      env:
        applitools.apiKey: ${{ secrets.apiKey }}
        USERNAME: ${{ secrets.username }}
        PASSWORD: ${{ secrets.password }}
      run: mvn -B clean compile package -P basic allure:report
    - uses: actions/upload-artifact@v1
      with:
          name: allure-report-basic
          path: target/site
    - name: run test with valid api key in 2 threads and assert single batch created
      env:
        applitools.apiKey: ${{ secrets.apiKey }}
        USERNAME: ${{ secrets.username }}
        PASSWORD: ${{ secrets.password }}
      run: |
        mvn -B clean compile package -P run-tests-in-parallel-threads
        mvn -B compile package -Dtest=OneBatchOnParallelTest allure:report
    - uses: actions/upload-artifact@v1
      with:
          name: allure-report-parallel-run
          path: target/site
