name: Deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Customize Maven repo settings
      run: cp .github/workflows/settings.xml ~/.m2
    - name: Install GPG key  
      run: echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
    - name: Deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        apiKey: ${{ secrets.apiKey }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
      run: mvn -B deploy
 
